name: myanmar_baydin
description: myanmar baydin

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  provider: ^3.1.0+1
  easy_localization: ^1.3.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2
  path_provider: ^1.4.4
  shared_preferences: ^0.5.4+5
  device_info: ^0.4.1+2
  scoped_model: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/my-MM.json
    - assets/en-US.json

  fonts:
    - family: Lato-black
      fonts:
        - asset: fonts/lato_black.ttf
          weight: 300

    - family: Lato-thin
      fonts:
        - asset: fonts/lato_thin.ttf
    - family: Lato-regular
      fonts:
        - asset: fonts/lato_regular.ttf
